# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QCursor
from NuevoProyecto import Ui_NuevoProyecto
from fbrowser import Ui_Dialog
from Documentacion import Ui_Documentacion
from Instrucciones import Ui_Instrucciones


def hide_show(win1, win2):
    win1.hide()
    win2.show()


class Ui_MainWindow(object):

    def nuevo_proyecto(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_NuevoProyecto()
        self.ui.setupUi(self.window)
        hide_show(MainWindow, self.window)
        self.ui.b_return.clicked.connect(lambda: hide_show(self.window, MainWindow))

    def c_proyecto(self):
        self.dialog = QtWidgets.QDialog()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.dialog)
        MainWindow.hide()
        self.dialog.show()
        self.ui.b_return.clicked.connect(lambda: hide_show(self.dialog, MainWindow))

    def instrucciones(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Instrucciones()
        self.ui.setupUi(self.window)
        hide_show(MainWindow, self.window)
        self.ui.b_return.clicked.connect(lambda: hide_show(self.window, MainWindow))

    def documentacion(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Documentacion()
        self.ui.setupUi(self.window)
        hide_show(MainWindow, self.window)
        self.ui.b_return.clicked.connect(lambda: hide_show(self.window, MainWindow))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Dimensionamiento Solar")
        MainWindow.resize(931, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(150, 90, 671, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.titulo.setFont(font)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        #botones
        self.b_nuevo_proyecto = QtWidgets.QPushButton(self.centralwidget)
        self.b_nuevo_proyecto.setGeometry(QtCore.QRect(360, 330, 161, 51))
        self.b_nuevo_proyecto.setObjectName("b_nuevo_proyecto")
        self.b_nuevo_proyecto.clicked.connect(self.nuevo_proyecto)
        self.b_nuevo_proyecto.setCursor(QCursor(QtCore.Qt.PointingHandCursor))

        self.b_cargar_proyecto = QtWidgets.QPushButton(self.centralwidget)
        self.b_cargar_proyecto.setGeometry(QtCore.QRect(360, 410, 161, 51))
        self.b_cargar_proyecto.setObjectName("b_cargar_proyecto")
        self.b_cargar_proyecto.clicked.connect(self.c_proyecto)
        self.b_cargar_proyecto.setCursor(QCursor(QtCore.Qt.PointingHandCursor))

        self.b_instrucciones = QtWidgets.QPushButton(self.centralwidget)
        self.b_instrucciones.setGeometry(QtCore.QRect(360, 490, 161, 51))
        self.b_instrucciones.setObjectName("b_instrucciones")
        self.b_instrucciones.clicked.connect(self.instrucciones)
        self.b_instrucciones.setCursor(QCursor(QtCore.Qt.PointingHandCursor))

        self.b_documentacion = QtWidgets.QPushButton(self.centralwidget)
        self.b_documentacion.setGeometry(QtCore.QRect(360, 560, 161, 51))
        self.b_documentacion.setObjectName("b_documentacion")
        self.b_documentacion.clicked.connect(self.documentacion)
        self.b_documentacion.setCursor(QCursor(QtCore.Qt.PointingHandCursor))


        #imagen inicio
        self.ph_inicio = QtWidgets.QLabel(self.centralwidget)
        self.ph_inicio.setGeometry(QtCore.QRect(0, 0, 931, 771))
        self.ph_inicio.setText("")
        self.ph_inicio.setPixmap(QtGui.QPixmap("inicio.jpg"))
        self.ph_inicio.setScaledContents(True)
        self.ph_inicio.setObjectName("ph_inicio")

        #mostrar
        self.ph_inicio.raise_()
        self.titulo.raise_()
        self.b_nuevo_proyecto.raise_()
        self.b_instrucciones.raise_()
        self.b_documentacion.raise_()
        self.b_cargar_proyecto.raise_()

        MainWindow.setCentralWidget(self.centralwidget)
        #Barra menu
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 931, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        #Barra estado
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Dimensionamiento Solar", "Dimensionamiento Solar"))
        self.titulo.setText(_translate("Dimensionamiento Solar", "DIMENSIONAMIENTO SOLAR ASISTIDO \nBY STUDENT ENERGY UTEC"))
        self.b_nuevo_proyecto.setText(_translate("Dimensionamiento Solar", "NUEVO PROYECTO"))
        self.b_instrucciones.setText(_translate("Dimensionamiento Solar", "INSTRUCCIONES"))
        self.b_documentacion.setText(_translate("Dimensionamiento Solar", "DOCUMENTACION"))
        self.b_cargar_proyecto.setText(_translate("Dimensionamiento Solar", "CARGAR PROYECTO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
